// Copyright Noah Butcher. All Rights Reserved.
#if WITH_DEV_AUTOMATION_TESTS

#include "Commandlets/EdgeOnlyBPSerializer.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "Engine/Blueprint.h"
#include "Misc/AutomationTest.h"
#include "Misc/EngineVersion.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "UObject/StrongObjectPtr.h"
#include "UObject/UObjectGlobals.h"

namespace UEMCP::SerializationOracleTests
{
	const FString AssetPath = TEXT("/Game/Owned/TransientDefaults");

	struct FFixture
	{
		TStrongObjectPtr<UBlueprint> Blueprint{NewObject<UBlueprint>(GetTransientPackage(), NAME_None, RF_Transient)};
		UEdGraphPin* Value = nullptr;
		UEdGraphPin* Empty = nullptr;
		UEdGraphPin* Linked = nullptr;
		UEdGraphPin* NestedValue = nullptr;

		FFixture()
		{
			UEdGraph* Root = NewObject<UEdGraph>(Blueprint.Get(), TEXT("Root"), RF_Transient);
			UEdGraph* Nested = NewObject<UEdGraph>(Root, TEXT("Nested"), RF_Transient);
			Blueprint->UbergraphPages.Add(Root);
			Root->SubGraphs.Add(Nested);
			Blueprint->FunctionGraphs.Add(NewObject<UEdGraph>(Blueprint.Get(), TEXT("Function"), RF_Transient));
			Blueprint->MacroGraphs.Add(NewObject<UEdGraph>(Blueprint.Get(), TEXT("Macro"), RF_Transient));
			Blueprint->DelegateSignatureGraphs.Add(NewObject<UEdGraph>(Blueprint.Get(), TEXT("Delegate"), RF_Transient));
			UEdGraphNode* First = NewObject<UEdGraphNode>(Root, NAME_None, RF_Transient);
			UEdGraphNode* Second = NewObject<UEdGraphNode>(Root, NAME_None, RF_Transient);
			UEdGraphNode* Third = NewObject<UEdGraphNode>(Nested, NAME_None, RF_Transient);
			First->NodeGuid = FGuid(0, 0, 0, 1);
			Second->NodeGuid = FGuid(0, 0, 0, 2);
			Third->NodeGuid = FGuid(0, 0, 0, 3);
			Root->Nodes.Add(First);
			Root->Nodes.Add(Second);
			Nested->Nodes.Add(Third);
			Value = First->CreatePin(EGPD_Input, FName(TEXT("int")), FName(TEXT("Value")));
			Empty = First->CreatePin(EGPD_Output, FName(TEXT("int")), FName(TEXT("Empty")));
			Linked = Second->CreatePin(EGPD_Input, FName(TEXT("int")), FName(TEXT("Linked")));
			NestedValue = Third->CreatePin(EGPD_Input, FName(TEXT("int")), FName(TEXT("NestedValue")));
			Value->PinId = FGuid(0, 0, 0, 0x11);
			Empty->PinId = FGuid(0, 0, 0, 0x12);
			Linked->PinId = FGuid(0, 0, 0, 0x21);
			NestedValue->PinId = FGuid(0, 0, 0, 0x31);
			Value->DefaultValue = TEXT("42");
			Value->AutogeneratedDefaultValue = TEXT("0");
			Empty->DefaultValue.Reset();
			Empty->AutogeneratedDefaultValue.Reset();
			Linked->DefaultValue = TEXT("7");
			Linked->AutogeneratedDefaultValue = TEXT("1");
			NestedValue->DefaultValue = TEXT("9");
			NestedValue->AutogeneratedDefaultValue = TEXT("2");
			Empty->MakeLinkTo(Linked);
		}
	};

	// Independent complete expectations: never derive fields from the serializer.
	TSharedPtr<FJsonObject> Expected(bool bDefaults)
	{
		const FString Value = bDefaults
			? TEXT(R"JSON({"name":"Value","direction":"EGPD_Input","default_value":"42","autogenerated_default_value":"0"})JSON")
			: TEXT(R"JSON({"name":"Value","direction":"EGPD_Input","linked_to":[]})JSON");
		const FString Empty = bDefaults
			? TEXT(R"JSON({"name":"Empty","direction":"EGPD_Output","default_value":"","autogenerated_default_value":""})JSON")
			: TEXT(R"JSON({"name":"Empty","direction":"EGPD_Output","linked_to":[{"node_guid":"00000000000000000000000000000002","pin_id":"00000000000000000000000000000021"}]})JSON");
		const FString Linked = bDefaults
			? TEXT(R"JSON({"name":"Linked","direction":"EGPD_Input","default_value":"7","autogenerated_default_value":"1"})JSON")
			: TEXT(R"JSON({"name":"Linked","direction":"EGPD_Input","linked_to":[{"node_guid":"00000000000000000000000000000001","pin_id":"00000000000000000000000000000012"}]})JSON");
		const FString NestedValue = bDefaults
			? TEXT(R"JSON({"name":"NestedValue","direction":"EGPD_Input","default_value":"9","autogenerated_default_value":"2"})JSON")
			: TEXT(R"JSON({"name":"NestedValue","direction":"EGPD_Input","linked_to":[]})JSON");
		const FString Json = FString::Printf(TEXT(R"JSON({
			"schema_version":"%s","engine_version":"","asset_path":"/Game/Owned/TransientDefaults",
			"graphs":{
				"Root":{"nodes":{"00000000000000000000000000000001":{"class_name":"EdGraphNode","pins":{
					"00000000000000000000000000000011":%s,"00000000000000000000000000000012":%s}},
					"00000000000000000000000000000002":{"class_name":"EdGraphNode","pins":{"00000000000000000000000000000021":%s}}}},
				"Root.Nested":{"nodes":{"00000000000000000000000000000003":{"class_name":"EdGraphNode","pins":{
					"00000000000000000000000000000031":%s}}}},
				"Function":{"nodes":{}},"Macro":{"nodes":{}},"Delegate":{"nodes":{}}
			}})JSON"), bDefaults ? TEXT("oracle-pin-defaults-v1") : TEXT("oracle-a-v2"), *Value, *Empty, *Linked, *NestedValue);
		TSharedPtr<FJsonObject> Object;
		if (!FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Json), Object)) return nullptr;
		Object->SetStringField(TEXT("engine_version"), FEngineVersion::Current().ToString());
		return Object;
	}

	bool MatchesExpected(const FString& Json, bool bDefaults)
	{
		TSharedPtr<FJsonObject> Actual;
		const TSharedPtr<FJsonObject> Want = Expected(bDefaults);
		if (!Want.IsValid() || !FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Json), Actual) || !Actual.IsValid()) return false;
		return FJsonValue::CompareEqual(FJsonValueObject(Actual), FJsonValueObject(Want));
	}
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FUEMCPOracleTopologyCompatibilityTest,
	"UEMCP.SerializationOracle.TopologyCompatibility",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)
bool FUEMCPOracleTopologyCompatibilityTest::RunTest(const FString& Parameters)
{
	using namespace UEMCP::SerializationOracleTests;
	for (const bool bPretty : {false, true})
	{
		FFixture Fixture;
		FString Before;
		TestTrue(TEXT("Legacy serializer succeeds"), UEMCP::SerializeBlueprintEdges(Fixture.Blueprint.Get(), AssetPath, bPretty, Before));
		TestTrue(TEXT("Complete legacy fields, nested graph and reciprocal links match"), MatchesExpected(Before, false));
		Fixture.Value->DefaultValue = TEXT("changed authored");
		Fixture.Value->AutogeneratedDefaultValue = TEXT("changed generated");
		FString After;
		TestTrue(TEXT("Legacy serializer still succeeds after defaults change"), UEMCP::SerializeBlueprintEdges(Fixture.Blueprint.Get(), AssetPath, bPretty, After));
		TestEqual(TEXT("Defaults do not change legacy output bytes"), After, Before);
	}
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FUEMCPOraclePinDefaultSupplementTest,
	"UEMCP.SerializationOracle.PinDefaultSupplement",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)
bool FUEMCPOraclePinDefaultSupplementTest::RunTest(const FString& Parameters)
{
	using namespace UEMCP::SerializationOracleTests;
	FFixture Fixture;
	TestTrue(TEXT("Linked pins belong to the same graph"), Fixture.Empty->GetOwningNode()->GetOuter() == Fixture.Linked->GetOwningNode()->GetOuter());
	TestTrue(TEXT("Nested defaults belong to a separate graph"), Fixture.NestedValue->GetOwningNode()->GetOuter() != Fixture.Linked->GetOwningNode()->GetOuter());
	FString TopologyBefore;
	TestTrue(TEXT("Baseline topology succeeds"), UEMCP::SerializeBlueprintEdges(Fixture.Blueprint.Get(), AssetPath, false, TopologyBefore));
	for (const bool bPretty : {false, true})
	{
		FString Json;
		TestTrue(TEXT("Supplement serializer succeeds"), UEMCP::SerializeBlueprintPinDefaults(Fixture.Blueprint.Get(), AssetPath, bPretty, Json));
		TestTrue(TEXT("Complete supplement preserves distinct and explicitly empty strings"), MatchesExpected(Json, true));
	}
	TestEqual(TEXT("Authored input unchanged"), Fixture.Value->DefaultValue, FString(TEXT("42")));
	TestEqual(TEXT("Generated input unchanged"), Fixture.Value->AutogeneratedDefaultValue, FString(TEXT("0")));
	TestTrue(TEXT("Both empty input strings unchanged"), Fixture.Empty->DefaultValue.IsEmpty() && Fixture.Empty->AutogeneratedDefaultValue.IsEmpty());
	TestEqual(TEXT("Linked authored input unchanged"), Fixture.Linked->DefaultValue, FString(TEXT("7")));
	TestEqual(TEXT("Linked generated input unchanged"), Fixture.Linked->AutogeneratedDefaultValue, FString(TEXT("1")));
	TestEqual(TEXT("Nested authored input unchanged"), Fixture.NestedValue->DefaultValue, FString(TEXT("9")));
	TestEqual(TEXT("Nested generated input unchanged"), Fixture.NestedValue->AutogeneratedDefaultValue, FString(TEXT("2")));
	FString TopologyAfter;
	TestTrue(TEXT("Topology succeeds after supplement"), UEMCP::SerializeBlueprintEdges(Fixture.Blueprint.Get(), AssetPath, false, TopologyAfter));
	TestEqual(TEXT("Supplement does not alter graph, node, pin or link identity"), TopologyAfter, TopologyBefore);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FUEMCPOracleInvalidBlueprintTest,
	"UEMCP.SerializationOracle.InvalidBlueprint",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)
bool FUEMCPOracleInvalidBlueprintTest::RunTest(const FString& Parameters)
{
	for (const bool bPretty : {false, true})
	{
		FString Json = TEXT("stale output");
		TestFalse(TEXT("Null topology input fails"), UEMCP::SerializeBlueprintEdges(nullptr, TEXT("/Game/Missing"), bPretty, Json));
		TestTrue(TEXT("Null topology clears output"), Json.IsEmpty());
		Json = TEXT("stale output");
		TestFalse(TEXT("Null defaults input fails"), UEMCP::SerializeBlueprintPinDefaults(nullptr, TEXT("/Game/Missing"), bPretty, Json));
		TestTrue(TEXT("Null defaults clears output"), Json.IsEmpty());
	}
	return true;
}
#endif
